language: python
dist: xenial
cache:
  - pip

before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install --upgrade -r requirements.txt
  - pip install .[all]
  - pip install pyyaml # for coveralls

before_script:
  - pip install --upgrade pytest pytest-cov coveralls telethon pytest-asyncio 
script: 
  - pytest --cov-report term-missing --cov=quizbot tests/

after_success:
  - coveralls