name: Test applicaiton

on: ["push", "pull_request"]

jobs:
  test:
    name: Test applicaiton
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install .[all]
          pip install pyyaml
          pip install --upgrade pytest pytest-cov telethon pytest-asyncio
      - name: Run tests
        run: pytest --cov-report term-missing --cov=quizbot tests/
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}